name: Auto bump version

on:
  push:
    branches:
      - main

jobs:
  auto_bump_version:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install bump2version
        run: pip install bump2version

      - name: Get new tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          CURRENT_VERSION=$(grep current_version .bumpversion.cfg | awk -F ' ' '{print $3}')
          if [ "$LATEST_TAG" == "$CURRENT_VERSION" ]; then
              NEW_TAG=$(echo $LATEST_TAG | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
              echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          elif [ "$(printf '%s\n' "$LATEST_TAG" "$CURRENT_VERSION" | sort -V | head -n 1)" != "$CURRENT_VERSION" ]; then
              echo "NEW_TAG=$CURRENT_VERSION" >> $GITHUB_ENV
          else
              NEW_TAG=$(echo $LATEST_TAG | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
              echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          fi

      - name: Bump version and push tag
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ env.NEW_TAG }}
          tag_exists_error: true
          message: "Latest release"
          github_token: ${{ secrets.ACTIONS_BOT_TOKEN }}