name: Auto tag on PR merge

on:
  pull_request:
    types:
      - closed

jobs:
  auto_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install bump2version
        run: pip install bump2version

      - name: Check if version was bumped manually
        run: |
          git fetch origin main
          VERSION_CHANGED=$(git diff origin/main...HEAD -- .bumpversion.cfg | grep -c -E "^\+current_version")
          if [ $VERSION_CHANGED -eq 0 ]; then
            echo "VERSION_NOT_BUMPED=true" >> $GITHUB_ENV
          else
            echo "VERSION_NOT_BUMPED=false" >> $GITHUB_ENV
          fi

      - name: Bump version and create a new tag
        if: env.VERSION_NOT_BUMPED == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email actions@github.com
          bump2version --no-tag --commit patch
          NEW_VERSION=$(cat .bumpversion.cfg | grep current_version | sed -r 's/^current_version\s*=\s*//')
          git tag $NEW_VERSION
          git push origin $NEW_VERSION
