name: Tag after PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  tag:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install bump2version
      run: pip install bump2version

    - name: Check if version was bumped manually
      id: check_version_bump
      run: |
        VERSION_CHANGED=$(git diff origin/main..HEAD -- .bumpversion.cfg | grep -c -E "^\+current_version")
        if [ $VERSION_CHANGED -eq 0 ]; then
          echo "VERSION_NOT_BUMPED=true" >> $GITHUB_ENV
        else
          echo "VERSION_NOT_BUMPED=false" >> $GITHUB_ENV
        fi

    - name: Bump patch version and tag
      if: steps.check_version_bump.outputs.version_bumped == 'false'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        bump2version --no-tag --commit patch
        NEW_VERSION=$(cat .bumpversion.cfg | grep current_version | sed -r 's/^current_version\s*=\s*//')
        git tag $NEW_VERSION
        git push origin $NEW_VERSION
